### PR TITLE
Relation_Upgrade 3000: Blossoming Hatred

### PR DESCRIPTION
**Pull request by meins111**

### CODE REVIEW

**Comment by seljukk** [comment]
Nicely done on the desc. And the choices to but I'm afraid there won't be enough space in the buttons (a) and (b). I like the additions so maybe there is a way to offload half of them to a (tt) tooltip when the player hovers over the choices?

**Comment by meins111** [comment]
Oh, there is a limit! What a shame. What is the limit though?

**Comment by Silverwing9** [comment]
I agree with seljukk, the options well exceed the button, but from an editing standpoint it's solid and I see no correction needed

**Review by DewarInverion — APPROVED** [review]
Full of imagery and emotion with a hint of chivalry.

**Pull request merged**
